services:
  gateway:
    build: ./gateway
    container_name: sgsdev-gateway
    ports:
      - "8080:80"
    depends_on:
      - monolito
      - login
      - salones
    restart: on-failure

  monolito:
    build: .
    container_name: sgsdev-monolito
    ports:
      - "5000:5000"

  login:
    build: ./services/login
    container_name: sgsdev-ms-login
    ports:
      - "5001:5001"

  salones:
    build: ./services/salones
    container_name: sgsdev-ms-salones
    ports:
      - "5002:5002"
